"use client";
import {useEffect,useRef} from "react";
import gsap from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);
const projects=[{n:"01",name:"FABULA",desc:"AI Market Intelligence Platform",tags:"PRODUCT DESIGN / AI / SAAS"},{n:"02",name:"LEGALO KR",desc:"Legal & Visa Assistant for Foreigners in Korea",tags:"PRODUCT DESIGN / MOBILE / LEGALTECH"},{n:"03",name:"MUDI BEAUTY 3D",desc:"Immersive K-Beauty E-commerce Experience",tags:"3D WEB / E-COMMERCE / UI UX"}];
const skills=[["01","SOFTWARE DEVELOPMENT","React · TypeScript · JavaScript · HTML / CSS · Tailwind CSS"],["02","PRODUCT DESIGN","Figma · UI / UX · Design Systems · Prototyping · Responsive UX"],["03","INTERACTIVE WEB DESIGN","GSAP · Scroll Animation · Micro-interactions · 3D Experiences"]];
export default function Home(){const root=useRef<HTMLDivElement>(null);useEffect(()=>{const ctx=gsap.context(()=>{gsap.from(".hero-line",{y:90,opacity:0,duration:1.15,stagger:.09,ease:"power4.out"});gsap.from(".portrait",{scale:.86,opacity:0,duration:1.4,ease:"power3.out"}); gsap.to(".orb",{x:60,y:-35,rotation:18,ease:"none",scrollTrigger:{trigger:"#hero",start:"top top",end:"bottom top",scrub:1}}); gsap.to(".role-track",{xPercent:-58,ease:"none",scrollTrigger:{trigger:"#roles",start:"top top",end:"+=2200",scrub:1,pin:true}});gsap.to(".portrait",{yPercent:12,scale:1.06,ease:"none",scrollTrigger:{trigger:"#hero",start:"top top",end:"bottom top",scrub:1}});gsap.utils.toArray<HTMLElement>(".reveal").forEach(el=>gsap.from(el,{y:70,opacity:0,duration:1,scrollTrigger:{trigger:el,start:"top 86%"}}));},root);return()=>ctx.revert()},[]);return <main ref={root}><div className="noise"/><nav className="container" style={{height:84,display:"flex",alignItems:"center",justifyContent:"space-between",position:"absolute",left:0,right:0,zIndex:20}}><a href="#hero" className="mono">MN / 26</a><div style={{display:"flex",gap:24,fontSize:12}} className="mono"><a href="#about">About</a><a href="#work">Work</a><a href="#contact">Contact</a></div></nav>
<section id="hero" style={{minHeight:"100svh",position:"relative",overflow:"hidden",display:"flex",alignItems:"flex-end",paddingBottom:"5vh"}}><div className="grid-bg" style={{position:"absolute",inset:0,opacity:.22}}/><div className="container" style={{position:"relative",zIndex:2}}><div className="mono hero-line muted" style={{marginBottom:18}}>Hello, I&apos;m Muzaffar Normurodov</div><h1 className="display" style={{margin:0}}><span className="hero-line" style={{display:"block"}}>SOFTWARE</span><span className="hero-line" style={{display:"block",paddingLeft:"10vw"}}>DEVELOPER</span></h1><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginTop:32,gap:24,flexWrap:"wrap"}}><p className="hero-line" style={{maxWidth:420,fontSize:18,lineHeight:1.45}}>I design and build digital products from idea to interface — combining product thinking, visual design and frontend engineering.</p><a className="pill mono hero-line" href="#work">Explore work ↓</a></div></div><div className="hero-visual portrait"><img src="https://raw.githubusercontent.com/MuzaffarJr/My-worklife/main/3fd00255-600f-4dc1-8377-ae79d235d474.png" alt="Muzaffar Normurodov portfolio hero" /></div></section>
<section id="about" className="container hairline" style={{padding:"130px 0"}}><div className="mono muted reveal">01 / About</div><div style={{display:"grid",gridTemplateColumns:"1fr minmax(280px,760px)",gap:40,marginTop:48}}><h2 className="section-title reveal" style={{margin:0}}>DESIGN.<br/>BUILD.<br/><span className="accent">LAUNCH.</span></h2><div className="reveal" style={{alignSelf:"end"}}><p style={{fontSize:"clamp(1.35rem,2.4vw,2.6rem)",lineHeight:1.15,letterSpacing:"-.035em"}}>Software Developer, Product Designer and Creative Web Designer focused on building clear, functional and visually distinctive digital products.</p><p className="muted" style={{maxWidth:620,lineHeight:1.7}}>My work connects interface planning, design systems, responsive UX and modern frontend development into one production-ready workflow.</p></div></div></section>
<section className="container hairline" style={{padding:"110px 0"}}><div className="mono muted reveal">02 / Expertise</div>{skills.map(s=><div key={s[0]} className="reveal" style={{display:"grid",gridTemplateColumns:"80px 1fr 1fr",gap:28,padding:"42px 0",borderBottom:"1px solid var(--line)",alignItems:"center"}}><div className="mono muted">{s[0]}</div><div style={{fontSize:"clamp(1.7rem,3.8vw,4rem)",letterSpacing:"-.045em"}}>{s[1]}</div><div className="muted" style={{lineHeight:1.7}}>{s[2]}</div></div>)}</section>
<section id="work" style={{padding:"110px 0"}}><div className="container"><div className="mono muted reveal">03 / Selected Work</div><h2 className="section-title reveal" style={{margin:"36px 0 80px"}}>SELECTED<br/>PROJECTS</h2>{projects.map(p=><article key={p.n} className="reveal project-card" style={{padding:"50px 0",borderTop:"1px solid var(--line)",display:"grid",gridTemplateColumns:"80px 1fr auto",gap:24,alignItems:"center",position:"relative"}}><span className="mono muted">{p.n}</span><div><h3 style={{fontSize:"clamp(2.4rem,6vw,6.5rem)",margin:0,letterSpacing:"-.06em"}}>{p.name}</h3><p className="muted">{p.desc}</p></div><span className="mono muted" style={{fontSize:11}}>{p.tags}</span></article>)}</div></section>
<section className="container hairline" style={{padding:"120px 0"}}><div className="mono muted reveal">04 / Stack</div><div className="reveal" style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:1,background:"var(--line)",marginTop:50,border:"1px solid var(--line)"}}>{[["DESIGN","Figma\nDesign Systems\nUI / UX\nPrototyping"],["DEVELOPMENT","React\nTypeScript\nJavaScript\nTailwind CSS"],["INTERACTION","GSAP\nScroll Animation\nMicro-interactions\n3D Experiences"]].map(x=><div key={x[0]} style={{background:"var(--bg)",padding:36,minHeight:280}}><div className="mono accent">{x[0]}</div><p style={{whiteSpace:"pre-line",fontSize:26,lineHeight:1.6}}>{x[1]}</p></div>)}</div></section>
<section id="contact" className="container hairline contact-section" style={{padding:"120px 0"}}>
<div className="mono muted reveal">05 / Contact & New Project</div>
<div className="contact-grid">
<div className="reveal"><h2 className="display" style={{margin:"45px 0"}}>LET&apos;S<br/><span className="accent">BUILD.</span></h2><p className="muted contact-intro">Have a project, startup idea or product that needs design and development? Send the details and let&apos;s discuss it.</p>
<div className="social-list">
<a href="mailto:muzaffaransoriy@gmail.com" className="social-link"><span className="social-icon">G</span><span><small>EMAIL</small>muzaffaransoriy@gmail.com</span><b>↗</b></a>
<a href="https://github.com/MuzaffarJr" target="_blank" rel="noreferrer" className="social-link"><span className="social-icon">GH</span><span><small>GITHUB</small>github.com/MuzaffarJr</span><b>↗</b></a>
<a href="https://instagram.com/muzaffar_n0rmurodov" target="_blank" rel="noreferrer" className="social-link"><span className="social-icon">IG</span><span><small>INSTAGRAM</small>@muzaffar_n0rmurodov</span><b>↗</b></a>
<a href="https://t.me/MuzaffarAnsoriy" target="_blank" rel="noreferrer" className="social-link"><span className="social-icon">TG</span><span><small>TELEGRAM</small>@MuzaffarAnsoriy</span><b>↗</b></a>
<a href="tel:+821083156444" className="social-link"><span className="social-icon">PH</span><span><small>PHONE</small>010-8315-6444</span><b>↗</b></a>
</div></div>
<form className="lead-form reveal" action="mailto:muzaffaransoriy@gmail.com" method="post" encType="text/plain">
<div><span className="mono accent">START A PROJECT</span><h3>Tell me what you&apos;re building.</h3><p className="muted">Share a few details. I&apos;ll use them to understand the project before we talk.</p></div>
<label>Your name<input name="name" required placeholder="Name / company"/></label>
<label>Email or Telegram<input name="contact" required placeholder="How can I reach you?"/></label>
<label>Project type<select name="project"><option>Website</option><option>Product / UI UX Design</option><option>Web Application</option><option>Startup / MVP</option><option>Branding</option><option>Other</option></select></label>
<label>Project details<textarea name="message" required rows={5} placeholder="Briefly describe your idea, goals and timeline..."/></label>
<button type="submit">SEND PROJECT REQUEST <span>↗</span></button>
</form></div></section>
<footer className="container hairline" style={{padding:"28px 0 40px",display:"flex",justifyContent:"space-between",gap:20,flexWrap:"wrap"}}><span className="mono">Muzaffar Normurodov © 2026</span><span className="mono muted">DESIGN · DEVELOPMENT · PRODUCT</span></footer></main>}